niches-directory = "niches"
igor-settings = "settings"

[[psychotropic.cues]]
name = "profile"

[[psychotropic.cues]]
name = "project-settings"
wait-for = ["profile"]

[[psychotropic.cues]]
name = "#main"

[[psychotropic.cues]]
name = "example"
